### ISSUE TITLE
Link on package in NuGet

### ISSUE THREAD

**Issue by ParadiseFallen** [OutSystems/WebView#160]

**Comment by joaompneves** [comment]
Can you provide more details?

**Comment by jenswet** [comment]
I think he is looking for a link to a nuget package of this project in the Readme. That would make it easier to start. I just searched for the same.

**Comment by joaompneves** [comment]
Here: 
https://www.nuget.org/packages/WebViewControl-Avalonia/
and
https://www.nuget.org/packages/WebViewControl-WPF/

**Comment by jenswet** [comment]
Hi @joaompneves 

Thank you very much for providing Nuget packages! 

Currently the build requirements are not linked in the package. I tried to solve it manually, but didn't succeed yet. You are using https://gitlab.com/joaompneves/cefglue for cefglue. This is a fork of https://gitlab.com/xiliumhq/chromiumembedded/cefglue. As far as I see only the original cefglue has nuget package. Do you have one for your fork too? Do I need any other requirements?

Does the current version of Webview require the 0.10-preview like the nuget package expects or could I also use the latest stable version?

Thanks and regards!

**Comment by joaompneves** [comment]
Hi @jenswet 
Yes I'm using my (https://gitlab.com/joaompneves/cefglue) cefglue fork which supports Avalonia.
You can find the cefglue packages on nuget too: https://www.nuget.org/packages/CefGlue.Avalonia/
Regarding Avalonia version used, you might have problems (probably building) using the stable one and so I recommend using the latest preview (if possible).

Feel free to submit a PR with updated build information if you find something missing or not clear.

**Comment by jenswet** [comment]
Hi @joaompneves 

Thanks for the quick help.

I've installed the second package too.
```
<PackageReference Include="WebViewControl-Avalonia" Version="2.75.66" />
<PackageReference Include="CefGlue.Avalonia" Version="75.1.87" />
```
After adding a basic webview to my app (copied from the example):
```
<webview:WebView Address="{Binding CurrentAddress}" />
```
following exception occurs:
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Xilium.CefGlue.Avalonia, Version=75.1.87.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Xilium.CefGlue.Avalonia, Version=75.1.87.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Unable to locate
File name: 'Xilium.CefGlue.Avalonia.dll'
```
Do you have any ideas about this? Looks like it cannot find the CefGlue package I have installed.

When it works I'll add a PR with updated Getting started instructions.

**Comment by joaompneves** [comment]
It looks like the packages weren't properly installed and the binaries copied to the output... can you confirm?

**Comment by jenswet** [comment]
The output folder looks like this:
Debug/
- netcoreapp3.1/
-- Avalonia.*.dll
-- WebViewControl.Avalonia.dll
-- x64/
--- Xilium.CefGlue.*.dll
--- Xilium.CefGlue.ProwserProcess.exe

So all Avalonia DLLs, the WebView DLL and CefGlue DLLs are there, but XefGlue is in a x64 subfolder unlike the Avalonia DLLs.

Is this supposed to run only under Windows and not cross platform? I am wondering because I see this BrowserProcess.exe under macOS.

**Comment by joaompneves** [comment]
It runs on both platforms but on macOS it requires proper packaging due to the way CEF works.

Check this script... I use in CefGlue:
https://gitlab.com/joaompneves/cefglue/-/blob/3770/CefGlue.Demo.Avalonia/bundle.sh

**Comment by joaompneves** [comment]
Check https://github.com/OutSystems/WebView/tree/macos-bundle

**Comment by joaompneves** [comment]
MacOS bundling changed and was simpified.
