### ISSUE TITLE
WebView doesent load properly on MacOS

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#165]
Hello!
I have issues when working with this WebView on MacOS.
After the app build start, I get an error
![image](https://user-images.githubusercontent.com/53405089/99100424-7889cc80-25e4-11eb-8cb2-af526baf0bc0.png)
After that, I manually add all the Xilium DLLs as assemblies. And when it builds, but when I click on the browser inside my app it crashes with a message
![image](https://user-images.githubusercontent.com/53405089/99100641-bc7cd180-25e4-11eb-8d7d-01e19b8136e5.png)
And I don't know how to solve this issue. To reproduce this you could just download your repo and run it, and you will face the same issue. Also would be nice if you would fix those errors when you firs build this project
![image](https://user-images.githubusercontent.com/53405089/99101350-2c8b5780-25e5-11eb-8c22-13ae9b1180a6.png)
(It's a win issue too). It's easy to fix it just by changing the version in .csproj to 75.1.87

**Comment by joaompneves** [comment]
Hi @Takoooooo 

Regarding the packages, I've uploaded the latest CefGlue packages. Since I do it manually they often get outdated. If you want you can build them from here: https://gitlab.com/joaompneves/cefglue

Regarding the issue of running this on OSX. The app needs to have a certain package structure.
Check the script I made for the CefGlue Demo: https://gitlab.com/joaompneves/cefglue/-/blob/3770/CefGlue.Demo.Avalonia/bundle.sh

**Comment by joaompneves** [comment]
Check https://github.com/OutSystems/WebView/tree/macos-bundle

**Comment by Takoooooo** [comment]
> Check https://github.com/OutSystems/WebView/tree/macos-bundle
This sample works well for me. Now ill try to figure out what do I need to do to make my app works the same good

**Comment by Takoooooo** [comment]
For debug, it works but for release, it fails.
![image](https://user-images.githubusercontent.com/53405089/99260870-a2313680-2824-11eb-86e3-543989a254b5.png)
I assume this occurs  because this script executes only for debug configuration, but I'm not sure
![image](https://user-images.githubusercontent.com/53405089/99261081-e6243b80-2824-11eb-8c36-82c9e415a6c1.png)

**Comment by Takoooooo** [comment]
Also, I would like to notice what demo from CefGlue.Demo.Avalonia doesn't work for macOS at all.
And for Rider(macOS) build fails for every configuration even for the macos-bundle branch. Mb because it doesn't recognize properly this in .csproj
![image](https://user-images.githubusercontent.com/53405089/99265498-6dc07900-282a-11eb-9da6-19fd3c9712bd.png)
(last rider version) .Mb I need to explicitly set newer MSBuild version but I don't know how

**Comment by joaompneves** [comment]
I could change that to support Release builds, but the bundle.sh is not yet production ready since it copies a lot more files than it is really needed.
Regarding Rider support, I used VS for mac.

I didn't change CefGlue.Demo.Avalonia yet.

**Comment by Takoooooo** [comment]
> I could change that to support Release builds, but the bundle.sh is not yet production ready since it copies a lot more files than it is really needed.
> Regarding Rider support, I used VS for mac.
> 
> I didn't change CefGlue.Demo.Avalonia yet.


That's great! Also if you need support I may help you to speed up this a bit. I would like to use your WebView in production so I really interested to make it work good

**Comment by Takoooooo** [comment]
Also, I think would be nice to exclude all those build.sh,tmp, and other folders what we would not really want to see in the project from all demos

**Comment by joaompneves** [comment]
Cool... I also use it production but with the aforementioned issues.

The MacOS packaging has several particularities as described here:
https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-mac-os-x

**Comment by joaompneves** [comment]
MacOS support was greatly improved.
