### ISSUE TITLE
SampleWebView.Avalonia doesnt startup on Linux

### ISSUE THREAD

**Issue by MartMet** [OutSystems/WebView#171]
Hi,

thanks for this awesome project. 

I wanted to try out the SampleWebView application for Avalonia on Linux (Mint). I have installed the dotnet core SDK 3.1.403 and execute the build/run via "dotnet run" in the  SampleWebView.Avalonia directory.

The build succeeded but the run failed with:

![grafik](https://user-images.githubusercontent.com/56763566/101388972-f463f580-38c0-11eb-92ad-7606405b12b8.png)

Am i missing any parameter to pass on cmd line?

**Comment by joaompneves** [comment]
Hi MartMet,

I haven't tested on Linux, only Windows and MacOS. It might probably need some work to work there, but I don't have a machine with linux, neither time to do it.
Pull requests are welcome but probably it also needs some tweaks here (before): https://gitlab.com/joaompneves/cefglue

**Comment by MartMet** [comment]
Thanks for your response. 

I have been digging a little deeper and added those requested libraries from [cef builds](https://cef-builds.spotifycdn.com/cef_binary_75.1.4%2Bg4210896%2Bchromium-75.0.3770.100_linux64_minimal.tar.bz2) to the debug dir. I also added the `chrome-sandbox` binary.

Although i have set the access rights via:
`sudo chown root chrome-sandbox` and `chmod 4755 chrome-sandbox` i still get this error:

![grafik](https://user-images.githubusercontent.com/56763566/102101160-8ff9e680-3e2a-11eb-8fbd-6e3cdcf3122f.png)

Maybe this information is helpful for someonelse.

**Comment by joaompneves** [comment]
I believe more work has to be done on the cefglue side.
There are some Operating System particularities that have to be worked out, eg:
https://gitlab.com/joaompneves/cefglue/-/blob/4183/CefGlue.Common/CefRuntimeLoader.cs#L30
