### ISSUE TITLE
Is it possible to get all cookies from browser?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#173]
I am searching for analog 
`Cef.GetGlobalCookieManager().VisitAllCookiesAsync()` from CefSharp.Here i found CefCookieManager class,but i cant find any way to get all cookies from it

**Comment by joaompneves** [comment]
This is the analog to that I believe:
https://gitlab.com/joaompneves/cefglue/-/blob/4183/CefGlue/Classes.Proxies/CefCookieManager.cs#L54
