### ISSUE TITLE
Nuget packages for CefGlue fork supporting Avalonia

### ISSUE THREAD

**Issue by amullins** [OutSystems/WebView#174]
Are the Nuget packages for your [CefGlue](https://gitlab.com/joaompneves/cefglue) fork published anywhere? I'm wanting to access the Cef browser host from the `WebView` control to execute `PrintToPDF` on the `CefBrowserHost`. I'd also like to update Avalonia to RC1.

Currently getting an exception when attempting to subclass WebView from within my Avalonia project that's referencing Avalonia RC1 packages. (I get the same error when attempting to call `ExecuteScript` on my `WebView`.
```CS0012	The type 'Control' is defined in an assembly that is not referenced. You must add a reference to assembly 'Avalonia.Controls, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'```

**Comment by joaompneves** [comment]
Hi @amullins 

You may find the packages published on nuget (https://www.nuget.org/packages/CefGlue.Avalonia/).

Probably you have mixed versions of Avalonia? Currently still using version 0.10.0-preview6.

**Comment by amullins** [comment]
I DID have Avalonia RC1 installed and reverted to preview-6. I had pulled down and made slight mods to _WebViewControl.Avalonia_ that allowed me to get an instance of the `CefBrowserHost`. This all worked under the _SampleWebView.Avalonia_ project (where I was bringing in _WebViewControl.Avalonia_ as a project reference. However, when I build a NuGet package (using VS built-in pack command) and install the package in another netcoreapp3.1 project, I get an assembly reference error (looking for _CefGlue.Common_). Is there a preferred method for packaging _WebViewControl-Avalonia_ via NuGet? I don't see any build scripts available and there isn't a nuspec file....

__More Information__
When bringing in the latest published version of _WebViewControl-Avalonia_ from NuGet,org (v. 2.85.10), package manager brings in the following packages...
- cef.redist.x64.85.3.12
- CefGlue.Avalonia.85.4183.8
- CefGlue.Common.85.4183.8
- WebViewControl-Avalonia.2.85.10
When loading a view containing a `WebView` control, I get a `FileNotFoundException` for `Xilium.CefGlue.Avalonia, Version 85.4183.7.0`
>System.IO.FileNotFoundException: Could not load file or assembly 'Xilium.CefGlue.Avalonia, Version=__85.4183.7.0__, Culture=neutral, PublicKeyToken=null'.

**Comment by joaompneves** [comment]
Seems that there is a version mismatch.
Can you share your repo, so I can take a look?
