### ISSUE TITLE
Is there any way to change User-Agent?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#175]
As I see such option present on the CefGlue (by `Cef.Initialize(mySettingsWithUserAgent);`) but in your wrapper implementation InitializeCef is private and I can't change User-Agent in any way

**Comment by joaompneves** [comment]
You have to do something like was done for eg. CachePath:
https://github.com/OutSystems/WebView/blob/108318700b0450c7ea15a12165cc168e2bf84f2d/WebViewControl/WebView.cs#L126

**Comment by Takoooooo** [comment]
> You have to do something like was done for eg. CachePath:
> https://github.com/OutSystems/WebView/blob/108318700b0450c7ea15a12165cc168e2bf84f2d/WebViewControl/WebView.cs#L126

What do you mean? do I need to copy all this initialization code, make changes in it, and invoke? I think this is not a very nice solution. I know what I'm able to set in settings, but it would be better to have an initialization method where I will be able to pass my settings as an argument to the method. Are there any temporal workarounds?

**Comment by joaompneves** [comment]
PR is welcome.
