### ISSUE TITLE
Url parameter in "Navigated" event sometimes doesn't match with "Address" property

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#177]
If you will set for example `https://deezer.com/` as Url on browser control for Avalonia, click on different buttons on the page you will see a mismatch 
![image](https://user-images.githubusercontent.com/53405089/103526881-32d1dd80-4e8a-11eb-8453-cc1d0a1be46d.png)

**Comment by joaompneves** [comment]
Can you detail a little bit more the sequence of events?

**Comment by Takoooooo** [comment]
I don't really understand what do you mean by the sequence of events, but I may tell you in more detail about how to reproduce such behavior. Just run the app with the setup written above, site will ask you about cookies, you click 'Agree', and then the "Navigated" event will be fired and url parameter will have such value as on the screenshot above

**Comment by joaompneves** [comment]
I cant reproduce that behavior using current master.

**Comment by joaompneves** [comment]
The navigated event is fired for each frame that the page has. In that specific scenario that page has some iframes and the navigated is being fired for them too. You can check the name of the frame that fires the Navigated event. The main frame has frameName == null.
