### ISSUE TITLE
May you publish NuGet with the last bundling improvement?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#179]

**Comment by joaompneves** [comment]
Do you know any public and free CI/CD pipeline where we could host the build?

**Comment by Takoooooo** [comment]
> Do you know any public and free CI/CD pipeline where we could host the build?

As far as I know, GitHub actions are free for public repositories, but being honest I haven't used it 
![image](https://user-images.githubusercontent.com/53405089/103911357-95d3a680-510e-11eb-861e-8b7f51e6f211.png)

**Comment by joaompneves** [comment]
Published
