### ISSUE TITLE
Is it possible to change Settings in the application runtime somehow?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#182]
To work around this in the XAML file I made ContentPresenter and passed my WebView to the ContentPresenter.Content property to be able to change my webview created by Avalonia with new webview with new UserAgent.But even this doesn't work for me because CefRuntimeLoader.IsLoaded after the first set up always would be true, even if I would manually dispose WebView created by Avalonia. And because of this, I cant change settings in any way at runtime. Maybe you know any way?

**Comment by joaompneves** [comment]
I dont know a way. You better check in the CEF forum, ways to do it:
Eg: https://magpcss.org/ceforum/viewtopic.php?f=6&t=14578
