### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by sauveura** [OutSystems/WebView#192]
Hello,
Everything is working fine on Windows, but I have a problem with libcef on Linux (Ubuntu 20.04).
"Unable to load shared library 'libcef'
Should I do something particular on linux ?
Have a nice day.

**Comment by joaompneves** [comment]
Hi sauveura,
Linux is not (yet) supported by the cefglue implementation used (https://gitlab.com/joaompneves/cefglue).
It works only on Windows and MacOS currently.

**Comment by sauveura** [comment]
Thank you for the fast answer.
