### ISSUE TITLE
Add ability to publish app which uses this library as a single-file app

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#193]
If we will publish the app with PublishSingleFile=true we will see such output.
![image](https://user-images.githubusercontent.com/53405089/108385855-be25e900-7214-11eb-9408-76167b44da3d.png)
For CefSharp it works.Also if we would try to put <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
in our csproj it would pack everything into one .exe(i assume because of this)
![image](https://user-images.githubusercontent.com/53405089/108386525-650a8500-7215-11eb-984f-36417e6444a8.png)
Also i would suggest to not include the README.txt into Release output

**Comment by joaompneves** [comment]
It works on windows but not on Mac. We tried that approach but that failed along with Mac app notarization.

**Comment by NemuruYama** [comment]
Sorry for opening this again, didn't know if it was better to do it here or a new issue.

In .NET 8, Producing on Single File simply crashes the application after opening.
It sometimes also simply doesn't open the application.

Without producing a single file, this works just fine.

I tested this on the sample.

**Comment by joaompneves** [comment]
Well nothing changed in this regard, so currently single-file app is not supported.

**Comment by NemuruYama** [comment]
You said "It works on windows", but I tried it on Windows 11 and it did not work

**Comment by joaompneves** [comment]
I meant that when we tried that approach it worked on windows. But we're not using that approach.
