### ISSUE TITLE
BrowserProcess get created every time i navigate between views

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#194]
I have an application that uses browser control quite a lot. I have different buttons on my view, and when you will click on any of them you will get navigated to view with browser control. When I click on those buttons each time new BrowserProcess gets created.
![image](https://user-images.githubusercontent.com/53405089/108389693-96d11b00-7218-11eb-9cb0-3b8597d79f2d.png)
For CefSharp only 3 BrowserPocesses would be running at the time

**Comment by joaompneves** [comment]
Can you reproduce in the sample?

**Comment by Takoooooo** [comment]
Sure, I would do that. But probably not today

**Comment by Takoooooo** [comment]
Check this.https://github.com/Takoooooo/SampleWebViewBug
Every button click would create a new BrowserProcess.Sorry for the dirty code

**Comment by joaompneves** [comment]
Its not a webview issue. You're creating anew webview on every button click and not disposing the old one.
