### ISSUE TITLE
How can i intercept resource load?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#195]
I would like to use something like RequestHandlers from CefSharp, I assume what I need to use BeforeResourceLoad event but every time I receive Response = null.
![image](https://user-images.githubusercontent.com/53405089/108835917-d4e38b80-75d8-11eb-95fb-a6aea8257a68.png)
or even
![image](https://user-images.githubusercontent.com/53405089/108836048-09574780-75d9-11eb-922d-28c7802692a1.png)

How to reproduce?
Just go to sample app->add a handler for BeforeResourceLoad event and that's all.

**Comment by joaompneves** [comment]
You would have to implement a CefSchemeHandlerFactory and a ResourceHandler similar to this:
https://github.com/OutSystems/WebView/compare/test-iframes-embedding#diff-9211f7d23d826fdca565b82ad1e07fe69f3f748057fe56956a5993a22cf08e96R39
