### ISSUE TITLE
When packing app into self-contained mode runtime would be packed for parent app and BrowserProcess

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#196]
Proof 
![image](https://user-images.githubusercontent.com/53405089/108837913-9d2a1300-75db-11eb-8cb1-990dfeeb0e03.png)
I'm not sure whether it at least possible but would be nice to reuse runtime from the parent app and don't pack it twice
e.g CefSharp just put their BrowserProcess into the directory where the parent app located and they are successfully sharing runtime between BrowserProcess and the parent app

**Comment by joaompneves** [comment]
Your app and the browser process app would have to be compiled in the exact same .net version. We tried that approach but was not manageable, it does not scale well.

**Comment by Takoooooo** [comment]
> Your app and the browser process app would have to be compiled in the exact same .net version. We tried that approach but was not manageable, it does not scale well.

But i am using net5.0 tfm for my project.As i see CefGlue has such tfm too
![image](https://user-images.githubusercontent.com/53405089/108843796-dc5c6200-75e3-11eb-90b9-83147a7c1975.png)

**Comment by joaompneves** [comment]
As I said it has to be the exact same .net build version... up to the revision, otherwise the app wont work.

**Comment by Takoooooo** [comment]
> As I said it has to be the exact same .net build version... up to the revision, otherwise the app wont work.

I'm sorry but i don't really understand what do you mean. If I have in my project tfm net5.0 and CefGlue has net5.0 tfm how can they differ?

**Comment by joaompneves** [comment]
They can differ on revision number fo the target .net version. 
Both CefGlueBrowser process and your app should have to be in the exact same .net version: eg: 5.0.1.200
If they differ, eg: if your app is compiled with 5.0.1.300 and CefGlueBrowserProcess with 5.0.1.200, it wont work.

**Comment by joaompneves** [comment]
Btw more details why here: https://github.com/dotnet/runtime/issues/46990
