### ISSUE TITLE
How can i clear all cookies at the time?

### ISSUE THREAD

**Issue by Takoooooo** [OutSystems/WebView#202]
I have such implementation of CefCookieVisitor.
![image](https://user-images.githubusercontent.com/53405089/110674927-0bc1c000-81db-11eb-949e-3b76503c106d.png)
I would like to clear all cookies when i need. Is there any option to do it? I tried disposing CefCookieVisitor, I tried setting the delete parameter in the Visit method but all of them don't really seem to solve the problem.

**Comment by joaompneves** [comment]
Better check on cef forums.
