### ISSUE TITLE
No async support for both way?

### ISSUE THREAD

**Issue by jingyiliu** [OutSystems/WebView#206]
Hi, guys,

How to call an async js function from c# and return results, and vice versa? Currently, it seems not work.

**Comment by joaompneves** [comment]
Hi,

Calling an async js function to gets its results requires a bit of work, and its not natural. Would would need to call the function but have a native object to get its results later.

Something along these lines:

```
var taskCompletionSource = new TaskCompletionSource<int>();

void SendResult(int result) => taskCompletionSource.SetResult(result);

webview.RegisterJavascriptObject("SendResults", SendResult);

var result = await TargetView.ExecuteScriptFunction("async () => { const result = await ...;  SendResults.Invoke(result)}");
```

Regarding the opposite, the C# method must be sync. You can call async code but the entry method called must wait for the results, before returning to the webview.
