### ISSUE TITLE
How can i check\subscribe to page fully loaded?

### ISSUE THREAD

**Issue by FeltMe** [OutSystems/WebView#214]
Hi. I have I faced the following problem:
I need to load full page html, so i use 

`Browser.LoadUrl("https://SomeUrl.com");`

Than i invoke JS script to get HTML

`var html = await webView.EvaluateScript<string>("document.documentElement.outerHTML");`

But result is not full html, becourse (IMHO) service use Single Page Application, and data(which i need) loaded in a few seconds later.
How can i check that data was loaded, cause use `Thread.Sleep(n);` not right to use.

Thanks for your time!

**Comment by joaompneves** [comment]
HI,

You better use a .net object to be notified when the SPA has loaded completely.
Something along these lines:

```
var loadCompletedTaskSource = new TaskCompletionSource<string>();
Browser.RegisterJavascriptObject("loadHandler", loadCompletedTaskSource);
Browser.LoadUrl("https://SomeUrl.com");

webView.ExecuteJavascript("
   function whenSPALoaded() {
       loadHandler.TrySetResult(document.documentElement.outerHTML);
   }
   
   spa.addEventListener("loaded", whenSPALoaded); // this is just the idea
");

var html = await loadCompletedTaskSource.Task;
```
