### ISSUE TITLE
Is there a way to enable popups?

### ISSUE THREAD

**Issue by dragonman117** [OutSystems/WebView#224]
The app I'm currently working on has me loading a web page that requires authentication. It has three methods of authentication, Sign in's with google, twitch, and apple. While two of them work, the google authentication seems when clicked claims the browser is blocking popups, launches the default browser, and then fails because no O-Auth client is found.

I've been trying to dig into the code base but so far have not been able to see where / how to turn this flag on and allow popups.

**Comment by joaompneves** [comment]
You can subscribe to the webview `PopupOpening` event and handle by yourself. When this event is not subscribed the default behavior is to open the default browser. When you subscribe the event, you get the url for the popup but you'll have to handle all by yourself - create a window with a new webview pointing to the provided url.
