### ISSUE TITLE
Exception on RegisterJavascriptObject

### ISSUE THREAD

**Issue by krissgjeng** [OutSystems/WebView#226]
I get an exception when i try to use the RegisterJavascriptObject function
i am using Avalonia 0.10.7, WebViewControl-Avalonia 2.91.8 and .net 5.0

i get the exception: 
`System.ArgumentException: 'An item with the same key has already been added. Key: setException'`

here is my code:
![cs_regjavatask](https://user-images.githubusercontent.com/37689829/134805335-a22d1d3c-cb22-44f3-880c-a67d22272e12.png)

i get a similar error even with just an object:
![cs_regjavaobj](https://user-images.githubusercontent.com/37689829/134805369-db41fc3c-46d0-49ec-a798-5ce7609bc390.png)

**Comment by joaompneves** [comment]
Create your own class to wrap the access to the object instance you want. There's an issue with those CLR objects that I'll fix it soon.
