### ISSUE TITLE
Blureffect on Avalonia and MacOS 27" 5K Display

### ISSUE THREAD

**Issue by DrWenz** [OutSystems/WebView#233]
are there any settings to minimize the blur effect ?

**Comment by joaompneves** [comment]
Have you tried the Sample? 

https://github.com/OutSystems/WebView/blob/master/SampleWebView.Avalonia/MainWindow.xaml.cs#L10
Are you using this setting off?

**Comment by DrWenz** [comment]
thx man, i was missing that 🍻
