### ISSUE TITLE
Setting height of WebView to the page height

### ISSUE THREAD

**Issue by milkywayfarer** [OutSystems/WebView#235]
How can I bind the WebView Control's height to the page maximum height? If I don't set any height, it makes it 0, and pages' height differs in runtime.

I use WebView as a part of my UserControl in Avalonia:
```
<Border>
   <ScrollViewer>
      <webview:WebView x:Name="webview" Address="..."/>
   </ScrollViewer>
</Border>
```

If you can't do it, then I need to know how to apply my ScrollBar style to the WebView.

**Comment by joaompneves** [comment]
You would have to communicate to c# (using the [RegisterJavascriptObject](https://github.com/OutSystems/WebView/blob/3738be5c4addedfce1167d02f29b26c08eefc43e/Tests.WebView/IsolatedJavascriptEvaluation.cs#L52)), the height of the page content and then use that value to set the control height.
