### ISSUE TITLE
GoBack and GoForward Not working

### ISSUE THREAD

**Issue by Shadow4walker** [OutSystems/WebView#243]
thanks for this control but I have some issue with 'GoBack and GoForward commands ' it's not working! is there's any quick solution for this

**Comment by joaompneves** [comment]
Hi,

Can you provide an example?
I tested using the following [sample](https://github.com/OutSystems/WebView/pull/244) and it works fine.

**Comment by Shadow4walker** [comment]
sorry for late response 
i'm facing this issue only when 'History Disabled' has been set 'IsHistoryDisabled="True"'

**Comment by joaompneves** [comment]
Great, because thats the IsHistoryDisabled goal, disable history navigation (back/forward) :)
