### ISSUE TITLE
Publishing creates only .exe output, while it expects to find a .dll

### ISSUE THREAD

**Issue by OsaPL** [OutSystems/WebView#249]
After opening the Avalonia app, the BrowserProcess just keeps crashing and restarting (to the point Win Defender will mark it as malware sometimes).
What is in the event viewer:
```
Description: A .NET application failed.
Application: Xilium.CefGlue.BrowserProcess.exe
Path: C:\Users\Osa-Master\RiderProjects\App\win-x64\CefGlueBrowserProcess\Xilium.CefGlue.BrowserProcess.exe
Message: The application to execute does not exist: 'C:\Users\Osa-Master\RiderProjects\App\win-x64\CefGlueBrowserProcess\Xilium.CefGlue.BrowserProcess.dll'.
```

The proj configuration:
```xml
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
```
Using: `dotnet publish -c release -r win-x64 -o "release/win-x64`

**Comment by joaompneves** [comment]
Seems like you're trying different build configs than what it's committed, the project is ready to build and run. The configs you're trying don't work with CEF (the native browser dependency).

**Comment by OsaPL** [comment]
Im not trying to build and publish this project, its my own project that is referencing this package that is having this issue after the publish.
I'll try and recreate the issue in a sample csproj.
