### ISSUE TITLE
ExecuteScript

### ISSUE THREAD

**Issue by query-wow** [OutSystems/WebView#250]
Boa tarde,
I wanted to ask if there was a way to execute Synchronous javascript scripts on the frame instead of executing them in bulk?

Best reguards

**Comment by joaompneves** [comment]
Hi

You have 2 methods: 
- execute: execute in bulk (webview will try to aggregate some scripts before handling over to the browser engine)
- evaluate: script are executed right away and you can get their results

**Comment by query-wow** [comment]
Thanks for the quick reply, i'm injecting jquery commands to the brower, in this case i don't particulary care about the response. Can Evaluate still be used in this context?  Because when i do, it feels like its waiting for something to happen and the changes take a long time to reflect, as if they were still using the queue
```csharp
 webView.EvaluateScript<object>("$('#typology').val('" + val+ "').trigger('change');");
```

**Comment by joaompneves** [comment]
If there's something on scripts queue it executes all the pending scripts and then the one you asked to evaluate.

**Comment by query-wow** [comment]
Thanks for the help, i used EvaluateScript and always return a int. This works for me!
