### ISSUE TITLE
[ WebViewControl.Avalonia ] Styles are broken for latest (0.10.14) version of Avalonia

### ISSUE THREAD

**Issue by FoggyFinder** [OutSystems/WebView#258]
Styles are definitely off. Steps to reproduce:

1. Bump version to `0.10.14` in `SampleWebView.Avalonia` project
2. Run

![_githubImg1](https://user-images.githubusercontent.com/16510738/175820725-5fae0572-9195-44fe-955e-9d2c2c360d81.jpg)

**Comment by joaompneves** [comment]
Please try adding here 
https://github.com/OutSystems/WebView/blob/master/SampleWebView.Avalonia/Program.cs#L10
the following line:

```
.With(new Win32PlatformOptions { UseWindowsUIComposition = false })

**Comment by FoggyFinder** [comment]
yep, it works. Thank you
