### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by Taybenberg** [OutSystems/WebView#262]
Hi, is there any way to add custom headers to requests?

**Comment by joaompneves** [comment]
Theoretically it is, but the WebView is not exposing that functionality.
If you want to submit a PR, can give you some hints:
1) expose access to the following method:
https://github.com/OutSystems/CefGlue/blob/4472/CefGlue/Classes.Proxies/CefRequest.cs#L176
2) in this class:
https://github.com/OutSystems/WebView/blob/master/WebViewControl/Request.cs

**Comment by joaompneves** [comment]
Thanks. It will soon be published to nuget: version 2.91.20

**Comment by Taybenberg** [comment]
Thanks, looking forward to the new version.

**Comment by joaompneves** [comment]
I meant 2.91.28
