### ISSUE TITLE
WebView not working with https links

### ISSUE THREAD

**Issue by milkywayfarer** [OutSystems/WebView#270]
Just tried to move my http link to https (same domain and page) and changing the WebView source, and now WebView opens this link in external browser. What can be the problem here? Every link with http protocol on my domain works flawlessly.

I'm using Avalonia and WebView 2.91.29

**Comment by joaompneves** [comment]
can you provide an example?

**Comment by milkywayfarer** [comment]
> can you provide an example?

The code that I use is a little bit hard to understand so I'll try to simplify it:
When my ViewModel changes, there is a code that will run:
```
var web = Variables.gameinfo[id].server + Variables.gameinfo[id].name + "/" + (CurrentLanguage.Index == 0 ? "ru" : "en") + ".html";
Debug.WriteLine(web); //used to make sure the URL is correct - it is, as it opens in external browser just OK
if(Variables.WebViewAddress != web)
{
...
Variables.WebViewAddress = web;
}
```
`Variables.WebViewAddress` triggers the `OnNext()` on `WebViewSubject` when `set`. `WebViewSubject` is bound to `WebView.AddressProperty` on my WebView.

Everything works fine with the link like `http://example.domain.com/page.html`. Links like  `https://example.domain.com/page.html` (literally changing one symbol) open in the external browser. SSL certs are fine. Page works fine in Chrome

**Comment by joaompneves** [comment]
Have you tried running the sample and load the same url?

**Comment by milkywayfarer** [comment]
> Have you tried running the sample and load the same url?

Just cloned it and used the URL, working fine. Is there any way for WebView to stop using external browser and just throw out an exception saying what went wrong?

**Comment by joaompneves** [comment]
Does the page contains popups?

This logic might be triggering:
https://github.com/OutSystems/WebView/blob/3738be5c4addedfce1167d02f29b26c08eefc43e/WebViewControl/WebView.InternalLifeSpanHandler.cs#L38

If there are popups, you need to deal with them. Likely you want to create a new window with a new webview to host the popup. To do that, subscribe to the `PopupOpening`webview event.
