### ISSUE TITLE
Few questions regarding using with Plex

### ISSUE THREAD

**Issue by derekantrican** [OutSystems/WebView#272]
I was testing out this control to see if I could use it with Plex. Here's a couple questions I had:

1. Looks like if I restart the application, I have to sign in again. I imagine I have to set some cookies somewhere? How do I do that?
2. I couldn't use the "Sign in with Google" button. Clicking the button in the sample application opens a Google auth window in my main browser but gives me "Error 401: invalid_client. The OAuth client was not found." Any way to solve this?
3. I was able to log in with my Plex credentials (not Google sign-in), but when I went to play a video I get the error "Error code: s4032 (Manifest)". Pulling up the DevTools gives me the following:
> GET https://192-168-0-16.0512ca29d5d34cd4ba2eb9beaae90974.plex.direct:32400/:/timeline?ratingKey=24&key=%2Flibrary%2Fmetadata%2F24&playbackTime=0&playQueueItemID=352&state=error&hasMDE=1&context=library%3Acontent.library&row=0&time=0&duration=1476000&X-Plex-Product=Plex%20Web&X-Plex-Version=4.93.3&X-Plex-Client-Identifier=5zntzj61pui9nbe78rxbngk3&X-Plex-Platform=Chrome&X-Plex-Platform-Version=91.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1080x922%2C2560x1440&X-Plex-Token=wvW-NB1s9bE6-q5K6byw&X-Plex-Language=en&X-Plex-Drm=none&X-Plex-Text-Format=plain&X-Plex-Provider-Version=5.1&X-Plex-Session-Identifier=dsauakj48hcbh6hwrqlv586c 400 (Bad Request)

The third is definitely the most problematic for me. Any tips?

**Comment by joaompneves** [comment]
Hi.

1) You need to set persist cache = true 
https://github.com/OutSystems/WebView/blob/3738be5c4addedfce1167d02f29b26c08eefc43e/WebViewControl/GlobalSettings.cs#L24

2) you need to handle the popup opening behavior... you can handle the event, create a new window and a new webview with the popup url
https://github.com/OutSystems/WebView/blob/affed565845ca42a78c021daaf08e307f81b66df/WebViewControl/WebView.cs#L74

3) don't know... seems very specific
