### ISSUE TITLE
WebView gets unresponsive

### ISSUE THREAD

**Issue by OlaSiv** [OutSystems/WebView#273]
I have a WebView control in my Avalonia app (Windows 10 desktop).
The page showing in the WebView has  a printer button.
Pushing the printer button opens the windows printer dialog as supposed to, but if the printer dialog is left open and you click on a link in the webview, the webview just stops responding. You can't click on anything.

Any idea what this could be?

**Comment by joaompneves** [comment]
Hi,

How can you click on the link after opening the print dialog? The print dialog is a modal dialog, so you can't click on anything else on the app until you dismiss the print dialog. Tested on macOS (don't have Windows now) and works as described and supposed.

**Comment by OlaSiv** [comment]
Partly my mistake. Turns out that OsrEnabled is turned on by default. If disabled, everything works fine.
With Osr enabled though, you can open the print dialog, click on another link or button in the window, then click cancel on the print dialog (close it) and now the webview is unresponsive.

**Comment by joaompneves** [comment]
Yeah, tested with OsrEnabled and the issue also happens on macOS. 
If you don't need to use OSR, you really shouldn't has it is less performant and has several issues.
