### ISSUE TITLE
Crash on 32 bit windows

### ISSUE THREAD

**Issue by redplane** [OutSystems/WebView#274]
Hi,

I'm using WebView control for my desktop application.
It can run successfully on Windows x64 in both Debug & Release mode.
I have published the application & ran successfully.

However, when I publish my application to x86 arch, the application crashed while starting the Webview control.
I have attached serilog to write the log to get the exception, but the application crashed without jumping to [global exception handler](https://docs.avaloniaui.net/docs/getting-started/unhandledexceptions).

When I access **Event viewer** on windows, I saw this exception:

- **Source**: .NET Runtime
```
CoreCLR Version: 6.0.922.41905
.NET Version: 6.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebViewControl.WebView.<>c__DisplayClass111_0.<InnerDispose>g__InternalDispose|0()
   at WebViewControl.WebView.InnerDispose()
   at WebViewControl.WebView.Finalize()
```

- **Source** Application Error

```
Faulting application name: EagleEye.Apps.Desktops.exe, version: 1.0.0.0, time stamp: 0x62ffe98c
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0fab6d21
Faulting process id: 0x173c
Faulting application start time: 0x01d8f3e78bc05f96
Faulting application path: <my_path>\bin\Release\net6.0\win-x86\EagleEye.Apps.Desktops.exe
Faulting module path: unknown
Report Id: 5530d569-1c9e-45e6-b5a7-f817e79925ac
Faulting package full name: 
Faulting package-relative application ID: 
```

Any solution please ?

**Comment by joaompneves** [comment]
Hi,

x86 architecture is not supported anymore
