### ISSUE TITLE
Is selenium control supported?

### ISSUE THREAD

**Issue by mStylias** [OutSystems/WebView#275]
Hey,
I am using selenium to control a webview in wpf and I was wondering if there support for such a feature in the webview for avalonia.

**Comment by joaompneves** [comment]
Hi,
I'm not sure what Selenium requires, but you can use a flavor of the [WebView with Remote Debugging Support](https://www.nuget.org/packages/WebViewControl-Avalonia-RemoteDebugSupport/) and set an environment variable - WEBVIEW_REMOTE_DEBUGGING_PORT - with the port debugging number.
