### ISSUE TITLE
Publish self-contained for Linux

### ISSUE THREAD

**Issue by EvanParallax** [OutSystems/WebView#278]
Hi there! I'm using .net 6 and avalonia 10. tryed to pulish self-contained for Linux x64 but had runtime error System.DllNotFoundException: Unable to load shared library 'libcef' or one of its dependencies.  There is no libcef.dll in folder, but if i publish for windows it is there and in windows it works correctly.  Is webView supporting Linux?

**Comment by joaompneves** [comment]
Hi,
As stated on the Readme, Linux is not supported.
