### ISSUE TITLE
input type date not displaying correctly

### ISSUE THREAD

**Issue by Amine-Smahi** [OutSystems/WebView#301]
Input type date is not showing it's content

<img width="119" alt="image" src="https://user-images.githubusercontent.com/24621701/226037176-fbcfd305-2b5d-4fcb-b58d-bd87615ea186.png">

**Comment by joaompneves** [comment]
Try with WebView.Settings.OsrEnabled = false;
Does it solve?

**Comment by Amine-Smahi** [comment]
It fixes the issue, but I lost the acrylic theme, as now the background is solid white while I want a more fluent design look,
What would you recommend 

<img width="118" alt="image" src="https://user-images.githubusercontent.com/24621701/226100848-5b5b0d0d-4c29-43ea-944f-8ed5e103a11c.png">

**Comment by joaompneves** [comment]
OsrEnabled = false is the recommended setting (you play directly with the real browser instead of a projected image of it), but with that you lose some visual blending capabilities such as transparency.
