### ISSUE TITLE
[request] Disable OSR by default, OSR mode causes multiple issues

### ISSUE THREAD

**Issue by jetspiking** [OutSystems/WebView#302]
**Hello,**

Off-screen rendering causes several issues in my experience, such as:
- Slower initial page loading.
- Keys such as " tab", "enter", "left", "right", shortcuts, etc. not working properly.
- WebView randomly turning unresponsive.

It seems to me that it would be more logical to disable OSR by default, due to the occuring issues. I spend quite a bit of time before I realized the OSR setting was the issue.

**Comment by joaompneves** [comment]
Hi,

Although OSR=false is indeed the recommended setting, but making that the default would be a breaking change, for existing consumers.
OSR=false also requires Avalonia to be setup in the following way:
https://github.com/OutSystems/WebView/blob/df6b7e1f27e01298265c470164351abed4672a96/SampleWebView.Avalonia/Program.cs#L10
