### ISSUE TITLE
[request] Any plan on making it compatible with AvaloniaUI 11? 

### ISSUE THREAD

**Issue by softeering** [OutSystems/WebView#303]
I pulled your repo and tried upgrading to AvaloniaUI 11-preview but while the project compiles with very minor changes, it fails at runtime. It seems like it's still looking for some AvaloniaUI version `0.10.17.0` assemblies that cannot be found

![image](https://user-images.githubusercontent.com/6609594/229063824-d26bae9f-af2d-4118-93b4-651306cff327.png)

Any idea of what the problem could be there?

Thanks

**Comment by joaompneves** [comment]
Hi,

WebView depends on [CefGlue](https://github.com/OutSystems/cefglue) which needs to be upgraded first.

**Comment by sandreas** [comment]
+1

**Comment by softeering** [comment]
thanks for the confirmation @joaompneves

**Comment by joaompneves** [comment]
there's a PR  https://github.com/OutSystems/WebView/pull/310 opened and a package published to address this
