### ISSUE TITLE
microphone permission denied

### ISSUE THREAD

**Issue by plmm016** [OutSystems/WebView#305]
I want to open microphone to speech，but no microphone permission box popped up to click, and  debug tools  show Uncaught (in promise) DOMException: Permission denied.

So, how can I get microphone permission in OutSystems/WebView

**Comment by joaompneves** [comment]
Hi,

According to [this](https://magpcss.org/ceforum/viewtopic.php?t=15794) you need to enable the "enable-media-stream" flag. Currently is not possible to enable extra CEF flags. Feel free to open a PR, for supporting extra custom flags. This is the place to start:
https://github.com/OutSystems/WebView/blob/master/WebViewControl/WebViewLoader.cs#L49

**Comment by plmm016** [comment]
收到~
