### ISSUE TITLE
Change cursor type over links

### ISSUE THREAD

**Issue by arnirichard** [OutSystems/WebView#306]
How do I change cursor type to Hand over links, something like
```
private void WebView_PointerMoved(object? sender, PointerEventArgs e)
{
      Point position = e.GetPosition(webView);

      // Check if the pointer is over a link
       if (webView.InputHitTest(position) is WebViewHitTestResult result && result.ElementType == WebViewElementType.Link)
       {
          // Change the cursor to a hand pointer
           webView.Cursor = new Cursor(StandardCursorType.Hand);
       }
      else
      {
           // Reset the cursor to the default
           webView.Cursor = new Cursor(StandardCursorType.Arrow);
      }
}
```

**Comment by joaompneves** [comment]
Hi,

You better use CSS for that. Hit-testing wont work on the browser as it is a completely different environment, which Avalonia doesn't know about.

**Comment by arnirichard** [comment]
Ok, I tried to add 'cursor: pointer;' style to all <a> tags. But it does not seem to work.

**Comment by joaompneves** [comment]
Did you tried on [this](https://github.com/OutSystems/WebView/tree/master/SampleWebView.Avalonia) sample app?

**Comment by joaompneves** [comment]
Set OSR = false?
https://github.com/OutSystems/WebView/blob/master/SampleWebView.Avalonia/MainWindow.xaml.cs#L10

**Comment by arnirichard** [comment]
Just to add, when I load the above project, the hand cursor is not visible over links.
However, in the sample app it works.

**Comment by joaompneves** [comment]
Setting OSR need to be one of the first things you do in your app

**Comment by arnirichard** [comment]
Closing
