### ISSUE TITLE
Nuget.config "Avalonia" feed needs to be changed

### ISSUE THREAD

**Issue by derekantrican** [OutSystems/WebView#313]
I had some trouble cloning this repo & restoring packages until I found https://github.com/VitalElement/AvalonStudio/issues/771

Apparently

https://github.com/OutSystems/WebView/blob/919df49e71e6ceba208972c5f116127cc9d1e4d7/Nuget.config#L17

Should be changed to `https://nuget.avaloniaui.net/repository/avalonia-all/index.json`

**Comment by joaompneves** [comment]
removed
