### ISSUE TITLE
Passing chromium flags

### ISSUE THREAD

**Issue by tkefauver** [OutSystems/WebView#317]
Just wanted to say THANK YOU!! for updating this to Avalonia11, I had been using CefNet but the repo disappeared recently and very glad your around!

For my use case there are a couple of chromium flags I pass (process-per-site and disable-features=NetworkService). Is there any way to pass those into Initialization?

**Comment by joaompneves** [comment]
There isn't a solution available out of the box, but essentially you need to properly pass those flags here:
https://github.com/OutSystems/WebView/blob/7cac5c3b84caa233cd846511bd2c9cffadf7741d/WebViewControl/WebViewLoader.cs#L49

**Comment by tkefauver** [comment]
Seems straightforward enough. I just didn't want to have to fork it. Thank you.

**Comment by joaompneves** [comment]
Feel free to open a PR
