### ISSUE TITLE
Browser Focus/TextInput

### ISSUE THREAD

**Issue by tkefauver** [OutSystems/WebView#321]
From the sample I can't input text into google search box (using OSR). 

I see [here](https://github.com/OutSystems/WebView/blob/7cac5c3b84caa233cd846511bd2c9cffadf7741d/WebViewControl/WebView.cs#L142C40-L142C40)  in WebView.cs that there are focus issues w/ OSR and commenting out that if statement still doesn't allow browser to take focus.

I notice when clicking onto the search box specifically, right before releasing the mouse the cursor does turn to an IBeam but then falls back to default.

Is there more places in the code preventing/unimplemented for OSR mode to get the focus? How can I get the browser to take focus? What are the problems that happen?

**Comment by joaompneves** [comment]
To be honest I don't know. It's been long time since I tried OSR.
