### ISSUE TITLE
Dialog box not displaying correctly

### ISSUE THREAD

**Issue by lwillems191** [OutSystems/WebView#324]
For some reason it seems like the buttons cannot be displayed correctly. Anybody know how to fix this?

![image](https://github.com/OutSystems/WebView/assets/136300869/a132602d-193d-4aa8-8d39-e2d31ce4204c)

**Comment by joaompneves** [comment]
Can you provide more details? The problem you're describing is vague

**Comment by lwillems191** [comment]
When using a confirm popup the Ok and Cancel text is not shown. only the blue button and black button

**Comment by joaompneves** [comment]
On mac works as expected.
<img width="960" alt="Screenshot 2024-01-02 at 11 59 30" src="https://github.com/OutSystems/WebView/assets/693294/befbeeb8-8b6c-4e29-9fc4-4451753ce58a">

**Comment by lwillems191** [comment]
Weird I am using it on Windows 10

**Comment by joaompneves** [comment]
Are you using a native js confirm popup right?
Have you checked with light theme on?
Have you tried on other machines?

**Comment by lwillems191** [comment]
I am using the native js confirm. It is also working fine in Edge and Chrome. 
I did try light theme, same problem.
I have not been able to test it on another machine.
