### ISSUE TITLE
[limit] Google: Couldn’t sign you in

### ISSUE THREAD

**Issue by emako** [OutSystems/WebView#328]
OS: Windows11

Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

![image](https://github.com/OutSystems/WebView/assets/24737061/921643ff-83b5-4296-bbac-80700e440702)

**Comment by joaompneves** [comment]
That was a google decision that closed the doors back in 2021:

https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html
