### ISSUE TITLE
Webview doesn't show in Avalonia 11

### ISSUE THREAD

**Issue by tarinnik** [OutSystems/WebView#330]
Hi,

I'm using Avalonia 11.0.7 and when I try to load the webview it results in a black screen. If I use WebViewControl version 2.106.10-avalonia11, I just get a black screen and nothing happens, but if I use version 2.117.5-avalonia11 I get a black screen and then the program exits with no errors given in Visual Studio.

I've uploaded the log file, it seems that the GPU process is crashing.

[logs.txt](https://github.com/OutSystems/WebView/files/14045333/logs.txt)

This is the code I'm using to create the webview.
```c#
WebView.Settings.OsrEnabled = false;
WebView.Settings.LogFile = "logs.txt";
AvaloniaXamlLoader.Load(this);
((WebView)Content!).Address = "http://example.org";
```

**Comment by joaompneves** [comment]
Have you tried the sample app?

**Comment by tarinnik** [comment]
Yeah the sample app works. Is there an example app for Avalonia 11?

**Comment by joaompneves** [comment]
This branch -> https://github.com/OutSystems/WebView/tree/avalonia11
