### ISSUE TITLE
Problems encountered in setting the OsrEnabled parameter

### ISSUE THREAD

**Issue by ych98** [OutSystems/WebView#334]
When OsrEnabled is set to false, it will cause the WebView overlay on top of other controls.
When OsrEnabled is set to true, win-x64 input and other operations are normal. 
However, on mac-arm64, the input cannot be undone, for example, I typed abc, I want backspace c, get ab, it has no feedback. I also tested Select All, moving the cursor left and right, and press Enter, but none of them worked.

**Comment by joaompneves** [comment]
OsrEnabled=true has several issues and its not recommended.  

As per OsrEnabled=false sitting on top of other controls thats the expected behavior, not a bug.

**Comment by ych98** [comment]
Is there a way to make my controls appear above the webview controls? Like the toast notification bar.

**Comment by joaompneves** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/6605
