### ISSUE TITLE
Setting WebView Properties

### ISSUE THREAD

**Issue by NorMoll** [OutSystems/WebView#340]
Hi and thanks for the huge effort in creating the control.

I have managed to set  AreDevToolEnabled but how would I set some of the other properties like IsPasswordAutosaveEnabled, IsGeneralAutofillEnabled etc and also how would I access Core Profile features like clearing the browser cache?

Thanks in advance.

**Comment by NorMoll** [comment]
Apologies, this is primarily for a cross platform Desktop app.

**Comment by joaompneves** [comment]
Hi,

I dont recognize those properties. All I see is that they seem to belong the the WebView2 control from microsoft, which has nothing to to with our WebView.
