### ISSUE TITLE
Can't input Chinese on Kylin V10

### ISSUE THREAD

**Issue by sandsc** [OutSystems/WebView#347]
Can not input Chinese in the HTML input box by using Chinese ime on Kylin V10. e.g. Sogou

**Comment by a6754z** [comment]
Did you start WebView sucessfully on Kylin V10? I tried but failed with error "Unable to find SubProcess".
No Xilium.CefGlue.BrowserProcess file can be found.

Did you meet this problem? If so, how did you get it resolved? Thank you.

**Comment by nicewillsuccess** [comment]
> Did you start WebView sucessfully on Kylin V10? I tried but failed with error "Unable to find SubProcess". No Xilium.CefGlue.BrowserProcess file can be found.
> 
> Did you meet this problem? If so, how did you get it resolved? Thank you.

Clone the code from this repository: https://github.com/OutSystems/CefGlue to your local machine. Right-click on the CefGlue.BrowserProcess project and select "Build". Then, copy the resulting .exe and .dll files to the root directory of your project.

**Comment by a6754z** [comment]
> > Did you start WebView sucessfully on Kylin V10? I tried but failed with error "Unable to find SubProcess". No Xilium.CefGlue.BrowserProcess file can be found.
> > Did you meet this problem? If so, how did you get it resolved? Thank you.
> 
> Clone the code from this repository: https://github.com/OutSystems/CefGlue to your local machine. Right-click on the CefGlue.BrowserProcess project and select "Build". Then, copy the resulting .exe and .dll files to the root directory of your project.

It works, thank you very much!

**Comment by joaompneves** [comment]
> Clone the code from this repository: https://github.com/OutSystems/CefGlue to your local machine. Right-click on the CefGlue.BrowserProcess project and select "Build". Then, copy the resulting .exe and .dll files to the root directory of your project.

The latest version shouldn't have those issues anymore.

**Comment by joaompneves** [comment]
Thats not a webview issue but more specifically a cefglue issue. Continue here: https://github.com/OutSystems/CefGlue/issues/156
