### ISSUE TITLE
How do you successfully upgrade from 3.120.3 to 3.120.4 on Windows11?

### ISSUE THREAD

**Issue by dhhunter** [OutSystems/WebView#348]
First of all I would like to thank you very much for your great work!  

I am attempting to upgrade a project from 3.120.3 to 3.120.4 and I am encountering the following exception:

FileNotFoundException: Unable to find SubProcess. Probed locations: 
...\bin\Debug\net8.0\CefGlueBrowserProcess\Xilium.CefGlue.BrowserProcess.exe
...\bin\Debug\net8.0\Xilium.CefGlue.BrowserProcess.exe
...\bin\Debug\net8.0\CefGlueBrowserProcess\Xilium.CefGlue.BrowserProcess.exe
...\bin\Debug\net8.0\Xilium.CefGlue.BrowserProcess.exe

What do I need to do to get the Xilium.CefGlue.BrowswerProcess.exe setup properly?  Thanks again!

**Comment by MichiKohlhaas** [comment]
I'm running into the same error where my application is unable to find this SubProcess. It's a new Avalonia project and I copied the code from the main view and view model.

**Comment by joaompneves** [comment]
Check the latest version: 3.120.5. We removed the support for dotnet 6 which was causing these build issues.

**Comment by dhhunter** [comment]
@joaompneves Thank you so very much, the update to 3.120.5 was quite smooth!  I hope that the removal of dotnet 6 support does not adversely affect too many of your users...
