### ISSUE TITLE
How to gracefully close the webview?

### ISSUE THREAD

**Issue by a6754z** [OutSystems/WebView#353]
Hi,

I have an appliation with multiple documents. Each document contains a WebView control configured with different addresses. But on Kylin V10 (based on Ubuntu 20.04), the application will crash when closing one document, no matter whether the WebView.Dispose() is called or not in document OnClosed method.

I'm wondering if this is a bug for the control, or any other way to close the WebView gracefully?

Thanks.

**Comment by joaompneves** [comment]
Hi, Do you have logs?

**Comment by a6754z** [comment]
[cef.log](https://github.com/user-attachments/files/17109789/cef.log)

Attached is the log. I just opened a document and then closed it.

**Comment by joaompneves** [comment]
I don't see any errors in the log.

**Comment by joaompneves** [comment]
Since the webview is a wrapper of CefGlue, and the issue would be likely there, I would recommend that you test in CefGlue and post the issue here:
https://github.com/OutSystems/CefGlue/issues
