### ISSUE TITLE
Crash when WebBrowser is hosted in a Avalonia TabControl and Tab is switched away (in Windows)

### ISSUE THREAD

**Issue by jogibear9988** [OutSystems/WebView#357]
If a Webbrowser inside of a Tab Control, and when I click in the UI to switch the tabs, I get the following crash:

      System.Runtime.InteropServices.COMException: 'Die Gruppe oder Ressource haben für diesen Vorgang nicht den richtigen Zustand. (0x8007139F)'

in english:

      The group or resource is not in the correct state to perform the requested operation

Stacktrace:

 	Avalonia.Base.dll!Avalonia.Collections.AvaloniaList<Avalonia.Visual>.Remove(Avalonia.Visual item)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(object content)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(Avalonia.AvaloniaPropertyChangedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Animation.Animatable.OnPropertyChangedCore(Avalonia.AvaloniaPropertyChangedEventArgs change)	Unknown
 	Avalonia.Base.dll!Avalonia.AvaloniaObject.RaisePropertyChanged<object>(Avalonia.AvaloniaProperty<object> property, Avalonia.Data.Optional<object> oldValue, Avalonia.Data.BindingValue<object> newValue, Avalonia.Data.BindingPriority priority, bool isEffectiveValue)	Unknown
 	Avalonia.Base.dll!Avalonia.PropertyStore.EffectiveValue<object>.SetAndRaiseCore(Avalonia.PropertyStore.ValueStore owner, Avalonia.StyledProperty<object> property, object value, Avalonia.Data.BindingPriority priority, bool isOverriddenCurrentValue, bool isCoercedDefaultValue)	Unknown
 	Avalonia.Base.dll!Avalonia.PropertyStore.EffectiveValue<object>.SetAndRaise(Avalonia.PropertyStore.ValueStore owner, Avalonia.PropertyStore.IValueEntry value, Avalonia.Data.BindingPriority priority)	Unknown
 	Avalonia.Base.dll!Avalonia.PropertyStore.ValueStore.ReevaluateEffectiveValue(Avalonia.AvaloniaProperty property, Avalonia.PropertyStore.EffectiveValue current, Avalonia.PropertyStore.IValueEntry changedValueEntry, bool ignoreLocalValue)	Unknown
 	Avalonia.Base.dll!Avalonia.Data.Core.UntypedBindingExpressionBase.PublishValue(object value, Avalonia.Data.Core.BindingError error)	Unknown
 	Avalonia.Base.dll!Avalonia.Data.TemplateBinding.PublishValue()	Unknown
 	Avalonia.Base.dll!Avalonia.Data.TemplateBinding.OnTemplatedParentPropertyChanged(object sender, Avalonia.AvaloniaPropertyChangedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.AvaloniaObject.RaisePropertyChanged<object>(Avalonia.AvaloniaProperty<object> property, Avalonia.Data.Optional<object> oldValue, Avalonia.Data.BindingValue<object> newValue, Avalonia.Data.BindingPriority priority, bool isEffectiveValue)	Unknown
 	Avalonia.Base.dll!Avalonia.AvaloniaObject.SetAndRaise<object>(Avalonia.DirectPropertyBase<object> property, ref object field, object value)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TabControl.SelectedContent.set(object value)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TabControl.UpdateSelectedContent.AnonymousMethod__45_0(object v)	Unknown
 	Avalonia.Base.dll!Avalonia.Reactive.AvaloniaPropertyObservable<object, object>.Subscribed(System.IObserver<object> observer, bool first)	Unknown
 	Avalonia.Base.dll!Avalonia.Reactive.LightweightObservableBase<object>.Subscribe(System.IObserver<object> observer)	Unknown
 	Avalonia.Base.dll!Avalonia.Reactive.Observable.Subscribe<object>(System.IObservable<object> source, System.Action<object> action)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TabControl.UpdateSelectedContent(Avalonia.Controls.Control container)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TabControl..cctor.AnonymousMethod__10_0(Avalonia.Controls.TabControl x, Avalonia.AvaloniaPropertyChangedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Reactive.LightweightObservableBase<Avalonia.AvaloniaPropertyChangedEventArgs<object>>.PublishNext(Avalonia.AvaloniaPropertyChangedEventArgs<object> value)	Unknown
 	Avalonia.Base.dll!Avalonia.AvaloniaObject.RaisePropertyChanged<object>(Avalonia.AvaloniaProperty<object> property, Avalonia.Data.Optional<object> oldValue, Avalonia.Data.BindingValue<object> newValue, Avalonia.Data.BindingPriority priority, bool isEffectiveValue)	Unknown
 	Avalonia.Base.dll!Avalonia.AvaloniaObject.RaisePropertyChanged<object>(Avalonia.DirectPropertyBase<object> property, object oldValue, object newValue)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Selection.SelectionModel<System.__Canon>.RaisePropertyChanged(string propertyName)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Selection.SelectionModel<object>.CommitOperation(Avalonia.Controls.Selection.SelectionModel<object>.Operation operation, bool raisePropertyChanged)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Selection.SelectionModel<System.__Canon>.EndBatchUpdate()	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Selection.SelectionModelExtensions.BatchUpdateOperation.Dispose()	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelection(int index, bool select, bool rangeModifier, bool toggleModifier, bool rightButton, bool fromFocus)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelection(Avalonia.Controls.Control container, bool select, bool rangeModifier, bool toggleModifier, bool rightButton, bool fromFocus)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelectionFromEventSource(object eventSource, bool select, bool rangeModifier, bool toggleModifier, bool rightButton, bool fromFocus)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TabControl.OnPointerPressed(Avalonia.Input.PointerPressedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Input.InputElement..cctor.AnonymousMethod__32_8(Avalonia.Input.InputElement x, Avalonia.Input.PointerPressedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Reactive.LightweightObservableBase<(object, Avalonia.Interactivity.RoutedEventArgs)>.PublishNext((object, Avalonia.Interactivity.RoutedEventArgs) value)	Unknown
 	Avalonia.Base.dll!Avalonia.Interactivity.EventRoute.RaiseEventImpl(Avalonia.Interactivity.RoutedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Interactivity.Interactive.RaiseEvent(Avalonia.Interactivity.RoutedEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Input.MouseDevice.MouseDown(Avalonia.Input.IMouseDevice device, ulong timestamp, Avalonia.Input.IInputElement root, Avalonia.Point p, Avalonia.Input.PointerPointProperties properties, Avalonia.Input.KeyModifiers inputModifiers, Avalonia.Input.IInputElement hitTest)	Unknown
 	Avalonia.Base.dll!Avalonia.Input.MouseDevice.ProcessRawEvent(Avalonia.Input.Raw.RawPointerEventArgs e)	Unknown
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.Send(System.Threading.SendOrPostCallback action, object arg, Avalonia.Threading.DispatcherPriority? priority)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.TopLevel.HandleInput(Avalonia.Input.Raw.RawInputEventArgs e)	Unknown
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.AppWndProc(nint hWnd, uint msg, nint wParam, nint lParam)	Unknown
 	Avalonia.Win32.dll!Avalonia.Win32.WindowImpl.WndProcMessageHandler(nint hWnd, uint msg, nint wParam, nint lParam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Avalonia.Win32.dll!Avalonia.Win32.Win32DispatcherImpl.RunLoop(System.Threading.CancellationToken cancellationToken)	Unknown
 	Avalonia.Base.dll!Avalonia.Threading.DispatcherFrame.Run(Avalonia.Threading.IControlledDispatcherImpl impl)	Unknown
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.PushFrame(Avalonia.Threading.DispatcherFrame frame)	Unknown
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken cancellationToken)	Unknown
 	Avalonia.Controls.dll!Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(string[] args)	Unknown
 	Avalonia.Controls.dll!Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(Avalonia.AppBuilder builder, string[] args, System.Action<Avalonia.Controls.ApplicationLifetimes.IClassicDesktopStyleApplicationLifetime> lifetimeBuilder)	Unknown
>	TiaAvaloniaProjectBrowser.Desktop.dll!TiaAvaloniaProjectBrowser.Desktop.Program.Main(string[] args) Line 15	C#

The error happens here:

				coreWebView.Profile.Deleted -= Profile_Deleted;

![image](https://github.com/user-attachments/assets/71c83058-629d-42ea-974c-4455b63334fa)

![image](https://github.com/user-attachments/assets/325cb0a4-1585-441d-9741-7fb2c79c4c60)

**Comment by joaompneves** [comment]
The browser control you're using its not this Webview. Its another control.

**Comment by jogibear9988** [comment]
Sorry.... I completely jumped to the wrong project... my fault
