### ISSUE TITLE
Adding Webview to .NET 8.0 Project

### ISSUE THREAD

**Issue by ska894** [OutSystems/WebView#358]
Hello,

I had a question regarding how to add the Webview package/project to an external solution. Once I add the `WebviewControl.Avalonia` package to my project `src` folder, I start to experience issues with building my application.

Other projects that I have included in the `src` folder work perfectly well with .NET 8.0 and Avalonia 11.1.3. For clarification, I am attempting to implement the https://github.com/OutSystems/WebView/tree/upgrade-to-net8 branch into my project.

Below is a snapshot of the initial issue I face when adding the project:
![Snapshot of Project](https://github.com/user-attachments/assets/ac2aa84e-68da-4ebf-950e-bfa42433bb73)

Once I add the project to the solution I get the error:
`NU1105	Unable to find project information for '..\AvaloniaDockApplication\src\WebviewControl.Avalonia\WebviewControl.Avalonia.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.`

However, after I run `dotnet restore`, I get a new set of errors related to the added project.
![After restoring and setting target framework](https://github.com/user-attachments/assets/5375ff97-3ba9-435e-8aeb-538a16aea442)

Considering this, is there any simple, step-by-step way of adding the `WebviewControl.Avalonia` package to my solution? I can provide more details if needed. Thank you.

**Comment by joaompneves** [comment]
Hi,

First of all that branch is already dead. Main is in .net8 for quite a while.
But the most important is that there's a nuget ready for consumption, you should use that.

**Comment by ska894** [comment]
Thank you so much for the very quick reply! I really appreciate this!

I have tried the nuget package instead, and everything was easy to integrate! However, I was also wondering about the Webview performance in relation to other packages. Most chromium Webview systems allow for 60 FPS performance on rendering tasks. However, when I implement the Webview package, I see that my performance drops to 30 FPS (with stats.js). Is this the maximum rendering speed available with the Webview or am I missing a specific setting? Or does this have something to do with Avalonia? For reference, I am running the application on Windows 10.

**Comment by joaompneves** [comment]
Make sure you setup it like this: 

https://github.com/OutSystems/WebView/blob/master/SampleWebView.Avalonia/MainWindow.xaml.cs#L10

**Comment by ska894** [comment]
Thank you so much for your help! I have just setup the webview as in the sample and everything is running at 60 FPS now! I am now closing this issue since all of my questions have been answered! Thank you so much again for this amazing project, and the very quick replies!
