### ISSUE TITLE
WebView 3.120.7 

### ISSUE THREAD

**Issue by Bobsoftru** [OutSystems/WebView#363]
PointerReleased stopped working. ZoomPercentage started working differently.

**Comment by joaompneves** [comment]
We need more details in order to understand the problems. A small repro project could also help.

**Comment by Bobsoftru** [comment]
This worked in 3.120.5, when switching to 3.120.7, the PointerReleased event stopped working and the ZoomPercentage coefficients started floating, if you want I will create a test program.
[a20241029.zip](https://github.com/user-attachments/files/17561117/a20241029.zip)

**Comment by joaompneves** [comment]
I made this change in version .6:
https://github.com/OutSystems/WebView/commit/f803ed4487e1413b0fb37ae4627283af2c7f2689#diff-609a4f7dcaf577d51039f4551869ed5c117bb64cf052064d4e65a9d71ac2ff04L12

Which basically changes the previous OSR behavior, which was on by default, but the recommendation is to be off.

If you want to revert to the previous behavior you need to set before loading the webview (early in the app lifecycle)
```
WebView.Settings.OsrEnabled = true;

**Comment by Bobsoftru** [comment]
Everything worked, I am extremely grateful.
