### ISSUE TITLE
RenderTargetBitmap is Blank

### ISSUE THREAD

**Issue by fls-eugene** [OutSystems/WebView#365]
I am trying to create a image from the WebView control, but the actual site is blank.

```cs
public static RenderTargetBitmap? CreateBitmap(this Visual Control)
{
    var w = (int)Control.Bounds.Width;
    var h = (int)Control.Bounds.Height;
    var bitmap = new RenderTargetBitmap(new PixelSize(w, h), new Vector(96, 96));
    bitmap.Render(Control);
    return bitmap;
}
```

Button click event:

```cs
var bm = this.CreateBitmap();
bm.Save("__WebView.jpg");
```

Sample:
[Test_WebView.zip](https://github.com/user-attachments/files/17589243/Test_WebView.zip)

**Comment by joaompneves** [comment]
For that to be possible you need to enable OSR

https://github.com/OutSystems/WebView/blob/0507f0368398355fd4329e6dbd19922ef04f5516/WebViewControl/GlobalSettings.cs#L73

**Comment by fls-eugene** [comment]
Thanks, but I am getting error by just enabling the Osr,

Error: System.InvalidOperationException: 'Cannot set OsrEnabled after WebView engine has been loaded'

Added the code to the click event
```cs
WebView.Settings.OsrEnabled = true; // This seems like wrong place
var bm = this.CreateBitmap();
bm.Save("__WebView.jpg");
``` 

Is there a sample for off-screen rendering perhaps?
