### ISSUE TITLE
HtmlLoad completed event?

### ISSUE THREAD

**Issue by fls-eugene** [OutSystems/WebView#366]
Is there a way to know when the page is done loading?

I am trying to render an image sequence of a local html page, after updating the html with some changes. 

Using Avalonia for Desktop.

Thanks

**Comment by fls-eugene** [comment]
The local html are generated static pages, which I don't have control over. I'll explore the option of creating copies of the html and adding in some JS and load those instead.

Is it possible to register to the Html's onload event?

**Comment by joaompneves** [comment]
Made a mistake, actually Navigated is equivalent to the onload event. For static pages that should work.

**Comment by fls-eugene** [comment]
Navigated does fire multiple times as you said it will (I assume it has to with the images), however, the html onload only fire once on same page using the following script as example:

```html
<script>
   window.addEventListener('load', function () { alert("Yay, loaded!") });
</script>
```

**Comment by joaompneves** [comment]
Navigated fires one time for each frame that the page has.

**Comment by fls-eugene** [comment]
Thanks
