### ISSUE TITLE
Load Html, not Url

### ISSUE THREAD

**Issue by fls-eugene** [OutSystems/WebView#369]
LoadHtml also calls LoadUrl. Is there a way to provide the actual Html syntax directly, or bind via View?
 
```cs
        public void LoadHtml(string html) {
            htmlToLoad = html;
            LoadUrl(DefaultLocalUrl, MainFrameName);
        }
```

**Comment by fls-eugene** [comment]
Sample

```cs

string html = 
"<!DOCTYPE html>" + 
"<html>" +
"<head>" +
"<title>Page Title</title>" +
"</head>" +
"<body>" +
"<h1>This is a Heading</h1>" +
"<p>This is a paragraph.</p>" +
"</body>" +
"</html>";

webView.LoadHtml(html);

```

**Comment by joaompneves** [comment]
What do you want to accomplish?

**Comment by fls-eugene** [comment]
The idea would be to load a .html into a C# property, which would serve like template for user changes. 
The user can then modify the template, ex: search and replace elements, add translation information, margins, padding, colors etc.

I am planning to use Html Agility Pack for changes to html.

Obviously, saving a new .html file for every user change is an option, but not my first choice. Ideally, using a MVVM approach keeps all changes in memory and would be a much faster solution.

**Comment by joaompneves** [comment]
So you wanted a property, instead of a method? That was a design decision, because call to the LoadHtml doesn't have immediate effect and also there's no getter. If you want to go with MVVM binding approach you need to implement a transformer on your side.

**Comment by fls-eugene** [comment]
Either a MVVM binding to a property or a method can work.
It is just that I don't see how the WebView control take direct html content, either via a method or property.

---

From original question:

> LoadHtml also calls LoadUrl. Is there a way to provide the actual Html syntax directly, or bind via View?

I apologize if my original question was unclear. Let try rephrase. 

The LoadHtml also loads a _Url or web address_, It does not load Html Content/Text/Markup/Code/Syntax (I don't know a better word sorry)

https://github.com/OutSystems/WebView/blob/0507f0368398355fd4329e6dbd19922ef04f5516/WebViewControl/WebView.cs#L317

I want to be able to provide the .html file's content, AKA, Html Syntax (Hypertext Markup Language) and not always load from an web address or file. Examples of Html Syntax can be found at https://www.w3schools.com/html

---

An example of such a property is The MS WebBrowser's DocumentText property
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.documenttext

**Comment by joaompneves** [comment]
LoadHtml receives a string that should represent an html which you want to load. its not an url!

**Comment by fls-eugene** [comment]
the LoadUrl inside the LoadHtml method threw me completely for some reason.
Thanks
