### ISSUE TITLE
LoadHtml does not load syles.css or images

### ISSUE THREAD

**Issue by fls-eugene** [OutSystems/WebView#371]
Hello

WebView.LoadHtml does not load external the stylesheets.

``` html
<head>
<link rel="stylesheet" href="styles.css">
````
Is there a way to get LoadHtml to also load the .css files? Nor does it load images in the html

Example:
[Test_WebViewHTML.zip](https://github.com/user-attachments/files/17649388/Test_WebViewHTML.zip)

Note: I have not tested .js scrips

**Comment by joaompneves** [comment]
Load html loads the html from a local url, so theres no way for the browser to know where to load the external resources.

I suggest that you look at some of the webview tests, namely these:

https://github.com/OutSystems/WebView/blob/master/tests/Tests.WebView/ResourcesLoading.cs#L10

**Comment by fls-eugene** [comment]
This feels a bit dirty, but it works so far

``` cs
 webView.BeforeResourceLoad += WebView_BeforeResourceLoad;

...

private void WebView_BeforeResourceLoad(WebViewControl.ResourceHandler resourceHandler)
{
    if (resourceHandler.Url.StartsWith("local"))
    {
        // Where to look for the resource files
        var root = $"{Environment.CurrentDirectory.Replace("\\", "/")}/Html";

        var file = $"{root}{resourceHandler.Url.Substring(17)}";
        resourceHandler.RespondWith(file);
    }
}
```
